name: 'Create GitHub Commit from Github App'
description: 'Create Commit'
author: 'qoomon'
branding:
  icon: git-commit
  color: blue

inputs:
  message:
    description: 'The commit message'
    required: true
  amend:
    description: 'Amend the last commit'
    default: 'false'
  allow-empty:
    description: 'Allow an empty commit'
    default: 'false'
  skip-empty:
    description: 'Skip action, if nothing to commit'
    default: 'false'

  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  working-directory:
    description: 'The working directory'
    required: true
    default: '.'
  remoteName:
    description: 'The remote name to create the commit at.'
    required: true
    default: 'origin'

outputs:
  commit:
    description: 'The commit hash, if a commit was created'

runs:
  using: 'node20'
  main: 'dist/index.js'
